---
- name: Deploy Flask Application
  hosts: pibm_server
  become: true
  remote_user: ubuntu

  vars:
    public_ip: "3.111.169.149"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python 3 pip
      apt:
        name: python3-pip
        state: present

    - name: Install Flask
      pip:
        name: flask
        state: present

    - name: Install Gunicorn3
      apt:
        name: gunicorn3
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Clone the repository
      git:
        repo: https://github.com/shubham2698/pibm_ra_13250.git
        dest: /home/ubuntu/pibm_ra_13250

    - name: Install project requirements
      pip:
        requirements: /home/ubuntu/pibm_ra_13250/requirements.txt

    - name: Rename flask_api.py to app.py
      command: mv /home/ubuntu/pibm_ra_13250/flask_api.py /home/ubuntu/pibm_ra_13250/app.py

    - name: Configure Nginx
      copy:
        content: |
          server {
              listen 80;
              server_name {{public_ip}};
          
              location / {
                  proxy_pass http://127.0.0.1:8000;
              }
          }
        dest: /etc/nginx/sites-enabled/flask-server.conf

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted


    - name: Start Gunicorn3 in the background
      shell: nohup gunicorn3 app:app > /dev/null 2>&1 &
      args:
        chdir: /home/ubuntu/pibm_ra_13250
